name: Setup Flutter

description: Set up Flutter environment

inputs:
  flutter-version:
    description: "Flutter version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ inputs.flutter-version }}
