name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  cd_pipeline:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: ./.github/actions/setup-flutter
        with:
          flutter-version: "3.19.6"

      - name: Prepare Ruby Environment
        run: |
          mkdir -p ~/ruby-tools
          mkdir -p ~/runner_temp
          mkdir -p ~/runner_workspace
          sudo chown -R $USER:$USER ~/ruby-tools ~/runner_temp ~/runner_workspace
        shell: bash

      - name: Install Ruby dependencies
        run: sudo apt-get install -y autoconf automake bison libffi-dev libgdbm-dev libncurses5-dev libsqlite3-dev libtool libyaml-dev pkg-config sqlite3
        shell: bash

      - name: Install Ruby using RVM
        run: |
          curl -sSL https://get.rvm.io | bash -s stable
          source ~/.rvm/scripts/rvm
          rvm install 3.1.2
          rvm use 3.1.2 --default
        shell: bash

      - name: Install Bundler
        run: gem install bundler -v 2.4.22
        shell: bash

      - name: Setup Fastlane
        run: |
          cd android
          bundle install
          cd ../..
        shell: bash

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run Linter
        uses: ./.github/actions/run-linter

      - name: Run Tests
        uses: ./.github/actions/run-tests

      - name: Build
        run: flutter build apk
        shell: bash

      - name: Deploy with Fastlane
        run: |
          cd android
          fastlane deploy_to_firebase
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        shell: bash

      - name: Send success notification to Slack
        if: success()
        uses: ./.github/actions/notify-slack
        with:
          status: "Success"
          color: "good"
          text: "Deployment successful!"
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send failure notification to Slack
        if: failure()
        uses: ./.github/actions/notify-slack
        with:
          status: "Failure"
          color: "danger"
          text: "Deployment failed!"
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
