name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.19.6"
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Setup Fastlane
        run: |
          cd android
          bundle install
          cd ../..
      - name: Install dependencies
        run: flutter pub get
      - name: Run Linter
        run: flutter analyze
      - name: Run Tests
        run: flutter test
      - name: Build
        run: flutter build apk

      - name: Deploy with Fastlane
        run: |
          cd android
          fastlane deploy_to_firebase
        env:
          FIREBASE_TOKEN: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCD+DWCdTLhhTHT\n8yDSk0B4Z10GNK6iWIgMUYg90CPz0QKVWX1PPD2i1Bq1XEBiugvoNj69yw2anKdu\no7HBLe5C8kmCZf6R6DG/pLeXnPVhk44phbS9/jSLQ3wuWZTM5mH5P6Ve+3OuGMST\ntN2x9ZjAsUaTp8ulljbv+CDR0lS6NaSP5tXE3pkgV6nXeBjCE5/y22Dg4oi/tjNr\ncfO2fl2iEUbWcfE50g6IYEahHM+8nQOI5oI0IAlbVffnsaBK2Odk3UO3bDZVql+5\ncYhRwBHZmukt3fuRdC7cRKnWf1gQx5r3ARgcL0oiU2w0xmgy3v/fFZgSpRemiPQb\ngIo1gbiJAgMBAAECggEANezJFLdGJL/z5esdmN4hxHFcIiqJx33MjdgNB1ETN9BK\nsXNhUGzJtMzd4wjAqHbkYa00wwIDW4+ynPOXsVvO1Z1Ca125Aa7zER/CA1pYLFiK\niS4A9ne2ycc4KYpiUr27AAnBTcgK83NcdAy+YDb+hZKKx9ATV2TDqxfldUdwZqvp\niex1XVJ9b4YhWw5Uvf9inYQncwBtIr43QOWJ2hn2OVe00j/jEFGwYTYFROfYpwis\nmzuYZRgteR0iKk7HAuyA/lMjVHh3I9Lul0HCboW4rrUPRkCJLwxB9JU7JRjjLysA\nKF6NNR0FPmJZn1b8T4Xn5lQCRzCiP1fvy0qx51uQZwKBgQC6QsWLs39es+EqG75b\nlgZA2QNEsyTTkAzlA4R95HrbyflTDOTozuGdIZTw648aURMo3kFhsgiTI6ssvq5y\n5WkvnDDf428DHBQqOUZuSgrV9xDYxuGCY63HUkQoqMCC2C8qw9hkPN02Dd65mz6j\ned/nk+TiJc+5TK069ARh7GbuxwKBgQC1YZUtUJhwjfRCwr2PVyewFyVT4q4+blhB\ncmlfoGRQTIA574sZTreOlUEwnmxRDPtadt5aoOCjGf5It0X+28E7pSr//LISDils\nD1uHT+ySfE6h7KKlzBYmcxmsN6nFQFZBIATOR253higAVhASZhC2wWA5smWTMkjm\nzb6rvQsOLwKBgQC2TUQsR7MSbdyj6iOWYHAeaEjapLwWlZcJTzgOP+I/3J86uhQS\nCOqpcITmiKe3ikLGbUJw7F+YJAEV+kukCQW6o5TyjRfKY2EZMpXMvIt+gCLtCTsO\n86DSxaIQaZqCdjU0FhtlgGzCyzCDWX8lYdPURNxwu7FkG7gxS0Q+07KrYQKBgQCt\n8obBLZD0KH8/Y0mt5RSvwJLQzwzx3JsRMOszhTuO8r7qUPtiauaIfEVHnjccx8lq\naaM24SBt6ui9zd3328KGNBF37FzOCfzZoCTUMOcdWM+EZM9bF82KVEojqkJLZDcU\nP+O7/C9Ju0QzhlXlfzK6QdvJmXfmYYwepOQeCa9HiwKBgGVUw62fJ0hMi/eW+I+M\nJWb/5sJtUmfJEG0EUJMgycZPjkvy7073p2tlsqPYiSHvyQhnaWqO4itn01bs1i5p\nvvOkBqL85nmAqwyYuqWLMYCqjYIcgKu+0fE6qd3duYljpSW7dKMN/M5vjWGPoCa9\n6y84Yy/jLdEGyTqV0Ofipgkk\n-----END PRIVATE KEY-----\n",
