name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  setup_env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.19.6"
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Setup Fastlane
        run: |
          cd android
          bundle install
          cd ..
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: flutter pub get
      - name: Run Linter
        run: flutter analyze
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: flutter test
      - name: Build
        run: flutter build apk
      - name: Deploy with Fastlane
        run: |
          cd android
          fastlane deploy_to_firebase
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: flutter build apk
      - name: Deploy with Fastlane
        run: |
          cd android
          fastlane deploy_to_firebase
