name: CI Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: ./.github/actions/setup-flutter
        with:
          flutter-version: "3.19.6"

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run Linter
        uses: ./.github/actions/run-linter

      - name: Run Tests
        uses: ./.github/actions/run-tests

      - name: Install Ruby and Bundle Audit
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          sudo gem install bundler -v 2.4.22
          sudo gem install bundle-audit
        shell: bash

      - name: Install OWASP Dependency-Check
        uses: ./.github/actions/install-owasp-dependency-check

      - name: Verify OWASP Dependency-Check Installation
        run: /usr/local/dependency-check/bin/dependency-check.sh --version
        shell: bash

      - name: Run OWASP Dependency-Check
        uses: ./.github/actions/run-owasp-dependency-check

      - name: Send success notification to Slack
        if: success()
        uses: ./.github/actions/notify-slack
        with:
          status: "Success"
          color: "good"
          text: "Lint, test, and OWASP Dependency-Check successful!"

      - name: Send failure notification to Slack
        if: failure()
        uses: ./.github/actions/notify-slack
        with:
          status: "Failure"
          color: "danger"
          text: "Lint, test, or OWASP Dependency-Check failed!"
