name: CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.19.6"

      - name: Install dependencies
        run: flutter pub get

      - name: Run Linter
        run: flutter analyze

      - name: Run Tests
        run: flutter test

      - name: Install OWASP Dependency-Check
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          curl -s https://api.github.com/repos/jeremylong/DependencyCheck/releases/latest | jq -r ".assets[] | select(.name | test(\"dependency-check\\-.*\\-release.zip\")) | .browser_download_url" | wget -i -
          unzip dependency-check-*-release.zip
          sudo mv dependency-check /usr/local/bin/dependency-check

      - name: Run OWASP Dependency-Check on Android Dependencies
        run: dependency-check --project "My Project" --scan ./android --format "ALL" --out dependency-check-report

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: dependency-check-report

      - name: Send success notification to Slack
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Lint, test, and dependency check successful!",
            "attachments": [
              {
                "color": "good",
                "fields": [
                  {"title": "Repository", "value": "${{ github.repository }}", "short": true},
                  {"title": "Branch", "value": "${{ github.ref }}", "short": true},
                  {"title": "Pull Request", "value": "${{ github.event.pull_request.title }}", "short": false},
                  {"title": "Commit Message", "value": "${{ github.event.head_commit.message }}", "short": false},
                  {"title": "Commit Author", "value": "${{ github.event.head_commit.author.name }}", "short": true},
                  {"title": "Job Status", "value": "${{ job.status }}", "short": true},
                  {"title": "Workflow", "value": "${{ github.workflow }}", "short": true},
                  {"title": "Job", "value": "${{ github.job }}", "short": true},
                  {"title": "Runner OS", "value": "${{ runner.os }}", "short": true},
                  {"title": "Run ID", "value": "${{ github.run_id }}", "short": true},
                  {"title": "Dependency Check Report", "value": "See attached report", "short": false}
                ],
                "actions": [
                  {
                    "type": "button",
                    "text": "Download Report",
                    "url": "${{ github.server_url }}/${{ github.repository }}/suites/${{ github.run_id }}/artifacts"
                  }
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send failure notification to Slack
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Lint, test, or dependency check failed!",
            "attachments": [
              {
                "color": "danger",
                "fields": [
                  {"title": "Repository", "value": "${{ github.repository }}", "short": true},
                  {"title": "Branch", "value": "${{ github.ref }}", "short": true},
                  {"title": "Pull Request", "value": "${{ github.event.pull_request.title }}", "short": false},
                  {"title": "Commit Message", "value": "${{ github.event.head_commit.message }}", "short": false},
                  {"title": "Commit Author", "value": "${{ github.event.head_commit.author.name }}", "short": true},
                  {"title": "Job Status", "value": "${{ job.status }}", "short": true},
                  {"title": "Workflow", "value": "${{ github.workflow }}", "short": true},
                  {"title": "Job", "value": "${{ github.job }}", "short": true},
                  {"title": "Runner OS", "value": "${{ runner.os }}", "short": true},
                  {"title": "Run ID", "value": "${{ github.run_id }}", "short": true},
                  {"title": "Dependency Check Report", "value": "See attached report", "short": false}
                ],
                "actions": [
                  {
                    "type": "button",
                    "text": "Download Report",
                    "url": "${{ github.server_url }}/${{ github.repository }}/suites/${{ github.run_id }}/artifacts"
                  }
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
