name: CI/CD

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Start Metrics Server
        run: |
          cd ../metrics-server
          nohup node server.js &

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.19.6"

      - name: Install dependencies
        run: flutter pub get

      - name: Run Linter
        run: flutter analyze

      - name: Run Tests
        run: flutter test

      - name: Install Ruby and Bundle Audit
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          sudo gem install bundler -v 2.4.22
          sudo gem install bundle-audit

      - name: Install OWASP Dependency-Check
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.3.2/dependency-check-7.3.2-release.zip
          unzip dependency-check-7.3.2-release.zip -d dependency-check
          sudo mv dependency-check/dependency-check /usr/local/dependency-check
          sudo chmod +x /usr/local/dependency-check/bin/dependency-check.sh
          echo "/usr/local/dependency-check/bin" >> $GITHUB_PATH

      - name: Verify OWASP Dependency-Check Installation
        run: /usr/local/dependency-check/bin/dependency-check.sh --version

      - name: Run OWASP Dependency-Check on Android Dependencies
        run: |
          mkdir -p dependency-check-report
          /usr/local/dependency-check/bin/dependency-check.sh --project "My Project" --scan ./android --format "ALL" --out dependency-check-report

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: dependency-check-report

      - name: Send success notification to Slack
        if: success()
        run: |
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -X POST -H 'Content-type: application/json' --data '{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Lint, test, and OWASP Dependency-Check successful!*"
                }
              },
              {
                "type": "section",
                "fields": [
                  {"type": "mrkdwn", "text": "*Repository:* \n${{ github.repository }}"},
                  {"type": "mrkdwn", "text": "*Branch:* \n${{ github.ref }}"},
                  {"type": "mrkdwn", "text": "*Commit Message:* \n${{ github.event.head_commit.message }}"},
                  {"type": "mrkdwn", "text": "*Commit Author:* \n${{ github.event.head_commit.author.name }}"},
                  {"type": "mrkdwn", "text": "*Job Status:* \nsuccess"},
                  {"type": "mrkdwn", "text": "*Workflow:* \n${{ github.workflow }}"},
                  {"type": "mrkdwn", "text": "*Job:* \n${{ github.job }}"},
                  {"type": "mrkdwn", "text": "*Runner OS:* \n${{ runner.os }}"},
                  {"type": "mrkdwn", "text": "*Run ID:* \n${{ github.run_id }}"}
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Dependency-Check Report",
                      "emoji": true
                    },
                    "url": "'"$RUN_URL"'"
                  }
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send failure notification to Slack
        if: failure()
        run: |
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -X POST -H 'Content-type: application/json' --data '{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Lint, test, or OWASP Dependency-Check failed!*"
                }
              },
              {
                "type": "section",
                "fields": [
                  {"type": "mrkdwn", "text": "*Repository:* \n${{ github.repository }}"},
                  {"type": "mrkdwn", "text": "*Branch:* \n${{ github.ref }}"},
                  {"type": "mrkdwn", "text": "*Commit Message:* \n${{ github.event.head_commit.message }}"},
                  {"type": "mrkdwn", "text": "*Commit Author:* \n${{ github.event.head_commit.author.name }}"},
                  {"type": "mrkdwn", "text": "*Job Status:* \nfailure"},
                  {"type": "mrkdwn", "text": "*Workflow:* \n${{ github.workflow }}"},
                  {"type": "mrkdwn", "text": "*Job:* \n${{ github.job }}"},
                  {"type": "mrkdwn", "text": "*Runner OS:* \n${{ runner.os }}"},
                  {"type": "mrkdwn", "text": "*Run ID:* \n${{ github.run_id }}"}
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
