name: CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  CI_PIPELINE:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.19.6"

      - name: Install dependencies
        run: flutter pub get

      - name: Run Linter
        run: flutter analyze

      - name: Run Tests
        run: flutter test

      - name: Send success notification to Slack
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Lint and test successful!",
            "attachments": [
              {
                "color": "good",
                "fields": [
                  {"title": "Repository", "value": "${{ github.repository }}", "short": true},
                  {"title": "Branch", "value": "${{ github.ref }}", "short": true},
                  {"title": "Pull Request", "value": "${{ github.event.pull_request.title }}", "short": false},
                  {"title": "Commit Message", "value": "${{ github.event.head_commit.message }}", "short": false},
                  {"title": "Commit Author", "value": "${{ github.event.head_commit.author.name }}", "short": true},
                  {"title": "Job Status", "value": "${{ job.status }}", "short": true},
                  {"title": "Workflow", "value": "${{ github.workflow }}", "short": true},
                  {"title": "Job", "value": "${{ github.job }}", "short": true},
                  {"title": "Runner OS", "value": "${{ runner.os }}", "short": true},
                  {"title": "Run ID", "value": "${{ github.run_id }}", "short": true}
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send failure notification to Slack
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Lint and test failed!",
            "attachments": [
              {
                "color": "danger",
                "fields": [
                  {"title": "Repository", "value": "${{ github.repository }}", "short": true},
                  {"title": "Branch", "value": "${{ github.ref }}", "short": true},
                  {"title": "Pull Request", "value": "${{ github.event.pull_request.title }}", "short": false},
                  {"title": "Commit Message", "value": "${{ github.event.head_commit.message }}", "short": false},
                  {"title": "Commit Author", "value": "${{ github.event.head_commit.author.name }}", "short": true},
                  {"title": "Job Status", "value": "${{ job.status }}", "short": true},
                  {"title": "Workflow", "value": "${{ github.workflow }}", "short": true},
                  {"title": "Job", "value": "${{ github.job }}", "short": true},
                  {"title": "Runner OS", "value": "${{ runner.os }}", "short": true},
                  {"title": "Run ID", "value": "${{ github.run_id }}", "short": true}
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
