name: Flutter Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.19.6"
      - name: Install dependencies
        run: flutter pub get
      - name: Run Linter
        run: flutter analyze
      - name: Run Tests
        run: flutter pub run lint
